# Generated by Django 6.0.2 on 2026-02-25 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('enseignant', models.CharField(max_length=200)),
                ('volumeHoraire', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
